import type { Metadata } from "next";
import { auth } from "@/auth";
import { Nav } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Todo Server Actions",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Nav session={session ?? undefined} />
        {children}
      </body>
    </html>
  );
}
